language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

  # PyPy versions
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
# command to install dependencies
install:
  - pip install .
# command to run tests
script: python3 -m unittest discover -s . -p "*_test.py"